"""Record installed package versions, without credentials or installation URLs."""
import importlib.metadata
import json
import platform
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    versions = {dist.metadata["Name"]: dist.version for dist in importlib.metadata.distributions()
                if dist.metadata.get("Name")}
    snapshot = {"python": platform.python_version(), "platform": platform.platform(),
                "packages": dict(sorted(versions.items(), key=lambda item: item[0].lower()))}
    lines = ["# Snapshot of the existing Windows environment; not a clean-install guarantee.",
             f"# Python {snapshot['python']}; generated by scripts/snapshot_environment.py"]
    lines += [f"{name}=={version}" for name, version in snapshot["packages"].items()]
    (ROOT / "requirements-lock-windows.txt").write_text("\n".join(lines)+"\n", encoding="utf-8")
    (ROOT / "reports/environment_snapshot.json").write_text(
        json.dumps(snapshot, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
    print(f"Recorded {len(versions)} installed packages; Python {snapshot['python']}")


if __name__ == "__main__":
    main()
